//! Lua API Registry and EmmyLua stubs generation.
//!
//! This module provides a mechanism to track all functions and variables
//! exposed to the Lua environment. It acts as a dual-purpose registry:
//! 1. Registers the actual Rust functions into the `mlua` runtime.
//! 2. Retains type and documentation metadata to generate EmmyLua stubs.

use mlua::{FromLuaMulti, IntoLua, IntoLuaMulti, Lua, Result, Table};

/// Represents the type of a Lua API item.
#[derive(Debug, Clone)]
pub enum LuaItemKind {
    /// A Lua function with typed parameters and a return type.
    Function {
        params: &'static [(&'static str, &'static str)],
        returns: &'static str,
    },
    /// A static variable or constant with a specific type.
    Variable { type_name: &'static str },
}

/// Metadata for a single item in the Lua API.
#[derive(Debug, Clone)]
pub struct LuaApiItem {
    /// The sub-table name (e.g., "sys", "fs", "drv").
    pub table: &'static str,
    /// The name of the function or variable (e.g., "os", "toml").
    pub name: &'static str,
    /// A human-readable description for the IDE tooltip.
    pub description: &'static str,
    /// An optional usage example.
    pub example: Option<&'static str>,
    /// The kind of the item (Function or Variable).
    pub kind: LuaItemKind,
}

/// The registry that holds all API metadata and assists in registration.
#[derive(Default)]
pub struct ApiRegistry {
    pub items: Vec<LuaApiItem>,
}

/// Removes common leading indentation from a multi-line string.
/// This allows using clean raw string literals in Rust code.
fn unindent(s: &str) -> Vec<String> {
    let mut lines: Vec<&str> = s.lines().collect();

    // Remove leading empty lines
    while !lines.is_empty() && lines[0].trim().is_empty() {
        lines.remove(0);
    }
    // Remove trailing empty lines
    while !lines.is_empty() && lines[lines.len() - 1].trim().is_empty() {
        lines.pop();
    }

    if lines.is_empty() {
        return vec![];
    }

    // Find the minimum indentation of non-empty lines
    let min_indent = lines
        .iter()
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.chars().take_while(|c| c.is_whitespace()).count())
        .min()
        .unwrap_or(0);

    lines
        .into_iter()
        .map(|line| {
            if line.trim().is_empty() {
                "".to_string()
            } else if line.len() >= min_indent {
                line[min_indent..].to_string()
            } else {
                line.trim().to_string()
            }
        })
        .collect()
}

impl ApiRegistry {
    /// Creates a new, empty API registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers a function in the given Lua table and records its metadata.
    pub fn register_func<F, A, R>(
        &mut self,
        table: &Table,
        lua: &Lua,
        meta: LuaApiItem,
        func: F,
    ) -> Result<()>
    where
        F: Fn(&Lua, A) -> Result<R> + 'static + Send + Sync,
        A: FromLuaMulti,
        R: IntoLuaMulti,
    {
        self.items.push(meta.clone());
        table.set(meta.name, lua.create_function(func)?)?;
        Ok(())
    }

    /// Registers a variable in the given Lua table and records its metadata.
    pub fn register_var<V>(
        &mut self,
        table: &Table,
        meta: LuaApiItem,
        value: V,
    ) -> Result<()>
    where
        V: IntoLua,
    {
        self.items.push(meta.clone());
        table.set(meta.name, value)?;
        Ok(())
    }

    /// Generates EmmyLua stubs as a formatted string.
    ///
    /// This string is ready to be written to a `.lua` file and consumed
    /// by tools like `lua-language-server`.
    pub fn generate_stubs(&self) -> String {
        let mut out = String::new();

        out.push_str("---@meta icefield\n");
        out.push_str("-- Automatically generated Icefield Lua API stubs.\n");
        out.push_str("-- Do not edit this file manually.\n\n");

        // --- Global Patches ---
        out.push_str("-- Extensions to standard Lua libraries\n\n");
        out.push_str("---@class string\n");
        out.push_str("local string = {}\n\n");
        out.push_str("--- Removes leading and trailing whitespace from a string.\n---\n");
        out.push_str("---@return string\n");
        out.push_str("function string.trim(s) end\n\n");

        // Build a list of all table paths, including intermediate ones.
        let mut table_paths = std::collections::HashSet::new();
        for item in &self.items {
            if item.table.is_empty() {
                continue;
            }
            let mut current_path = String::new();
            for part in item.table.split('.') {
                if current_path.is_empty() {
                    current_path.push_str(part);
                } else {
                    current_path.push('.');
                    current_path.push_str(part);
                }
                table_paths.insert(current_path.clone());
            }
        }

        let mut tables: Vec<String> = table_paths.into_iter().collect();
        tables.sort_unstable();

        out.push_str("---@class icefield\n");
        // Top-level fields
        for t in &tables {
            if !t.contains('.') {
                out.push_str(&format!("---@field {} icefield.{}\n", t, t));
            }
        }
        out.push_str("icefield = {}\n\n");

        // Generate top-level items (where table is empty)
        let root_items = self.items.iter().filter(|i| i.table.is_empty());
        Self::generate_items_stubs(&mut out, root_items, "");

        for t in &tables {
            out.push_str(&format!("---@class icefield.{}\n", t));

            // Sub-fields for intermediate tables
            let prefix = format!("{}.", t);
            for sub in &tables {
                if let Some(rest) = sub.strip_prefix(&prefix)
                    && !rest.contains('.')
                {
                    out.push_str(&format!(
                        "---@field {} icefield.{}\n",
                        rest, sub
                    ));
                }
            }

            out.push_str(&format!("icefield.{} = {{}}\n\n", t));

            let table_items =
                self.items.iter().filter(|i| i.table == t.as_str());
            Self::generate_items_stubs(&mut out, table_items, t);
        }

        out
    }

    /// Helper to generate stubs for a specific list of items.
    fn generate_items_stubs<'a>(
        out: &mut String,
        items: impl Iterator<Item = &'a LuaApiItem>,
        table_name: &str,
    ) {
        let prefix = if table_name.is_empty() {
            "icefield".to_string()
        } else {
            format!("icefield.{}", table_name)
        };

        for item in items {
            // Multi-line description support with unindent
            for line in unindent(item.description) {
                if line.is_empty() {
                    out.push_str("---\n");
                } else {
                    out.push_str(&format!("--- {}\n", line));
                }
            }

            if let Some(ex) = item.example {
                out.push_str("---\n---@example\n");
                for line in unindent(ex) {
                    if line.is_empty() {
                        out.push_str("---\n");
                    } else {
                        out.push_str(&format!("--- {}\n", line));
                    }
                }
            }

            match &item.kind {
                LuaItemKind::Variable { type_name } => {
                    out.push_str("---\n");
                    out.push_str(&format!("---@type {}\n", type_name));
                    out.push_str(&format!(
                        "{}.{} = nil\n\n",
                        prefix, item.name
                    ));
                }
                LuaItemKind::Function { params, returns } => {
                    out.push_str("---\n");
                    let mut param_names = Vec::new();
                    for (p_name, p_type) in *params {
                        out.push_str(&format!(
                            "---@param {} {}\n",
                            p_name, p_type
                        ));
                        param_names.push(*p_name);
                    }
                    out.push_str(&format!("---@return {}\n", returns));
                    out.push_str(&format!(
                        "function {}.{}({}) end\n\n",
                        prefix,
                        item.name,
                        param_names.join(", ")
                    ));
                }
            }
        }
    }
}
