//! Lua API Registry and EmmyLua stubs generation.
//!
//! This module provides a mechanism to track all functions and variables
//! exposed to the Lua environment. It acts as a dual-purpose registry:
//! 1. Registers the actual Rust functions into the `mlua` runtime.
//! 2. Retains type and documentation metadata to generate EmmyLua stubs.

use mlua::{FromLuaMulti, IntoLua, IntoLuaMulti, Lua, Result, Table};

/// Represents the type of a Lua API item.
#[derive(Debug, Clone)]
pub enum LuaItemKind {
    /// A Lua function with typed parameters and a return type.
    Function {
        params: &'static [(&'static str, &'static str)],
        returns: &'static str,
    },
    /// A static variable or constant with a specific type.
    Variable { type_name: &'static str },
}

/// Metadata for a single item in the Lua API.
#[derive(Debug, Clone)]
pub struct LuaApiItem {
    /// The sub-table name (e.g., "sys", "fs", "drv").
    pub table: &'static str,
    /// The name of the function or variable (e.g., "os", "toml").
    pub name: &'static str,
    /// A human-readable description for the IDE tooltip.
    pub description: &'static str,
    /// The kind of the item (Function or Variable).
    pub kind: LuaItemKind,
}

/// The registry that holds all API metadata and assists in registration.
#[derive(Default)]
pub struct ApiRegistry {
    pub items: Vec<LuaApiItem>,
}

impl ApiRegistry {
    /// Creates a new, empty API registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers a function in the given Lua table and records its metadata.
    pub fn register_func<F, A, R>(
        &mut self,
        table: &Table,
        lua: &Lua,
        meta: LuaApiItem,
        func: F,
    ) -> Result<()>
    where
        F: Fn(&Lua, A) -> Result<R> + 'static + Send + Sync,
        A: FromLuaMulti,
        R: IntoLuaMulti,
    {
        self.items.push(meta.clone());
        table.set(meta.name, lua.create_function(func)?)?;
        Ok(())
    }

    /// Registers a variable in the given Lua table and records its metadata.
    pub fn register_var<V>(
        &mut self,
        table: &Table,
        meta: LuaApiItem,
        value: V,
    ) -> Result<()>
    where
        V: IntoLua,
    {
        self.items.push(meta.clone());
        table.set(meta.name, value)?;
        Ok(())
    }

    /// Generates EmmyLua stubs as a formatted string.
    ///
    /// This string is ready to be written to a `.lua` file and consumed
    /// by tools like `lua-language-server`.
    pub fn generate_stubs(&self) -> String {
        let mut out = String::new();

        out.push_str("---@meta icefield\n");
        out.push_str("-- Automatically generated Icefield Lua API stubs.\n");
        out.push_str("-- Do not edit this file manually.\n\n");

        // Build a list of all table paths, including intermediate ones.
        let mut table_paths = std::collections::HashSet::new();
        for item in &self.items {
            let mut current_path = String::new();
            for part in item.table.split('.') {
                if current_path.is_empty() {
                    current_path.push_str(part);
                } else {
                    current_path.push('.');
                    current_path.push_str(part);
                }
                table_paths.insert(current_path.clone());
            }
        }

        let mut tables: Vec<String> = table_paths.into_iter().collect();
        tables.sort_unstable();

        out.push_str("---@class icefield\n");
        // Top-level fields
        for t in &tables {
            if !t.contains('.') {
                out.push_str(&format!("---@field {} icefield.{}\n", t, t));
            }
        }
        out.push_str("icefield = {}\n\n");

        for t in &tables {
            out.push_str(&format!("---@class icefield.{}\n", t));

            // Sub-fields for intermediate tables
            let prefix = format!("{}.", t);
            for sub in &tables {
                if let Some(rest) = sub.strip_prefix(&prefix) {
                    if !rest.contains('.') {
                        out.push_str(&format!(
                            "---@field {} icefield.{}\n",
                            rest, sub
                        ));
                    }
                }
            }

            out.push_str(&format!("icefield.{} = {{}}\n\n", t));

            let table_items =
                self.items.iter().filter(|i| i.table == t.as_str());
            for item in table_items {
                out.push_str(&format!("--- {}\n", item.description));
                match &item.kind {
                    LuaItemKind::Variable { type_name } => {
                        out.push_str(&format!("---@type {}\n", type_name));
                        out.push_str(&format!(
                            "icefield.{}.{} = nil\n\n",
                            t, item.name
                        ));
                    }
                    LuaItemKind::Function { params, returns } => {
                        let mut param_names = Vec::new();
                        for (p_name, p_type) in *params {
                            out.push_str(&format!(
                                "---@param {} {}\n",
                                p_name, p_type
                            ));
                            param_names.push(*p_name);
                        }
                        out.push_str(&format!("---@return {}\n", returns));
                        out.push_str(&format!(
                            "function icefield.{}.{}({}) end\n\n",
                            t,
                            item.name,
                            param_names.join(", ")
                        ));
                    }
                }
            }
        }

        out
    }
}
